/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcj_teana_opengles_VideoCore */

#ifndef _Included_com_zcj_teana_opengles_VideoCore
#define _Included_com_zcj_teana_opengles_VideoCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zcj_teana_opengles_VideoCore
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zcj_teana_opengles_VideoCore_init
  (JNIEnv *, jobject);

/*
 * Class:     com_zcj_teana_opengles_VideoCore
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zcj_teana_opengles_VideoCore_play
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
