/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcj_teana_pcm_Control */

#ifndef _Included_com_zcj_teana_pcm_Control
#define _Included_com_zcj_teana_pcm_Control
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zcj_teana_pcm_Control
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zcj_teana_pcm_Control_init
        (JNIEnv *, jobject);

/*
 * Class:     com_zcj_teana_pcm_Control
 * Method:    play
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zcj_teana_pcm_Control_play
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zcj_teana_pcm_Control
 * Method:    pause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zcj_teana_pcm_Control_pause
        (JNIEnv *, jobject);

/*
 * Class:     com_zcj_teana_pcm_Control
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zcj_teana_pcm_Control_stop
        (JNIEnv *, jobject);

/*
 * Class:     com_zcj_teana_pcm_Control
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zcj_teana_pcm_Control_destroy
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
