/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcj_teana_ffmpeg_FFmpegCore */

#ifndef _Included_com_zcj_teana_ffmpeg_FFmpegCore
#define _Included_com_zcj_teana_ffmpeg_FFmpegCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zcj_teana_ffmpeg_FFmpegCore
 * Method:    getFFmpegVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zcj_teana_ffmpeg_FFmpegCore_getFFmpegVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_zcj_teana_ffmpeg_FFmpegCore
 * Method:    getFFmpegConfiguration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zcj_teana_ffmpeg_FFmpegCore_getFFmpegConfiguration
  (JNIEnv *, jobject);

/*
 * Class:     com_zcj_teana_ffmpeg_FFmpegCore
 * Method:    getFFmpegLicense
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zcj_teana_ffmpeg_FFmpegCore_getFFmpegLicense
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
